# Generated by Django 5.2.4 on 2025-12-06 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key', 'date'], name='analytics_u_session_a60cd0_idx'),
        ),
    ]
