export const AVAILABLE_PERMISSIONS = [
    // Users
    { codename: 'view_user', name: 'Can view user' },
    { codename: 'add_user', name: 'Can add user' },
    { codename: 'change_user', name: 'Can change user' },
    { codename: 'delete_user', name: 'Can delete user' },
    { codename: 'view_department', name: 'Can view department' },
    { codename: 'add_department', name: 'Can add department' },
    { codename: 'change_department', name: 'Can change department' },
    { codename: 'delete_department', name: 'Can delete department' },
    { codename: 'view_employee', name: 'Can view employee' },
    { codename: 'add_employee', name: 'Can add employee' },
    { codename: 'change_employee', name: 'Can change employee' },
    { codename: 'delete_employee', name: 'Can delete employee' },
    { codename: 'view_role', name: 'Can view role' },
    { codename: 'add_role', name: 'Can add role' },
    { codename: 'change_role', name: 'Can change role' },
    { codename: 'delete_role', name: 'Can delete role' },
    { codename: 'view_landlord', name: 'Can view landlord' },
    { codename: 'add_landlord', name: 'Can add landlord' },
    { codename: 'change_landlord', name: 'Can change landlord' },
    { codename: 'delete_landlord', name: 'Can delete landlord' },
    { codename: 'view_agent', name: 'Can view agent' },
    { codename: 'add_agent', name: 'Can add agent' },
    { codename: 'change_agent', name: 'Can change agent' },
    { codename: 'delete_agent', name: 'Can delete agent' },

    // Analytics
    { codename: 'view_listingstat', name: 'Can view listing stat' },
    { codename: 'add_listingstat', name: 'Can add listing stat' },
    { codename: 'change_listingstat', name: 'Can change listing stat' },
    { codename: 'delete_listingstat', name: 'Can delete listing stat' },
    { codename: 'view_listingviewevent', name: 'Can view listing view event' },
    { codename: 'add_listingviewevent', name: 'Can add listing view event' },
    { codename: 'change_listingviewevent', name: 'Can change listing view event' },
    { codename: 'delete_listingviewevent', name: 'Can delete listing view event' },
    { codename: 'view_usersession', name: 'Can view user session' },
    { codename: 'add_usersession', name: 'Can add user session' },
    { codename: 'change_usersession', name: 'Can change user session' },
    { codename: 'delete_usersession', name: 'Can delete user session' },

    // Billing
    { codename: 'view_subscription', name: 'Can view subscription' },
    { codename: 'add_subscription', name: 'Can add subscription' },
    { codename: 'change_subscription', name: 'Can change subscription' },
    { codename: 'delete_subscription', name: 'Can delete subscription' },
    { codename: 'view_tier', name: 'Can view tier' },
    { codename: 'add_tier', name: 'Can add tier' },
    { codename: 'change_tier', name: 'Can change tier' },
    { codename: 'delete_tier', name: 'Can delete tier' },

    // Campuses
    { codename: 'view_campus', name: 'Can view campus' },
    { codename: 'add_campus', name: 'Can add campus' },
    { codename: 'change_campus', name: 'Can change campus' },
    { codename: 'delete_campus', name: 'Can delete campus' },
    { codename: 'view_city', name: 'Can view city' },
    { codename: 'add_city', name: 'Can add city' },
    { codename: 'change_city', name: 'Can change city' },
    { codename: 'delete_city', name: 'Can delete city' },
    { codename: 'view_neighborhood', name: 'Can view neighborhood' },
    { codename: 'add_neighborhood', name: 'Can add neighborhood' },
    { codename: 'change_neighborhood', name: 'Can change neighborhood' },
    { codename: 'delete_neighborhood', name: 'Can delete neighborhood' },

    // Interests
    { codename: 'view_interest', name: 'Can view interest' },
    { codename: 'add_interest', name: 'Can add interest' },
    { codename: 'change_interest', name: 'Can change interest' },
    { codename: 'delete_interest', name: 'Can delete interest' },

    // Listings
    { codename: 'view_listing', name: 'Can view listing' },
    { codename: 'add_listing', name: 'Can add listing' },
    { codename: 'change_listing', name: 'Can change listing' },
    { codename: 'delete_listing', name: 'Can delete listing' },
    { codename: 'view_room', name: 'Can view room' },
    { codename: 'add_room', name: 'Can add room' },
    { codename: 'change_room', name: 'Can change room' },
    { codename: 'delete_room', name: 'Can delete room' },
    { codename: 'view_amenity', name: 'Can view amenity' },
    { codename: 'add_amenity', name: 'Can add amenity' },
    { codename: 'change_amenity', name: 'Can change amenity' },
    { codename: 'delete_amenity', name: 'Can delete amenity' },
    { codename: 'view_category', name: 'Can view category' },
    { codename: 'add_category', name: 'Can add category' },
    { codename: 'change_category', name: 'Can change category' },
    { codename: 'delete_category', name: 'Can delete category' },
    { codename: 'view_listingimage', name: 'Can view listing image' },
    { codename: 'add_listingimage', name: 'Can add listing image' },
    { codename: 'change_listingimage', name: 'Can change listing image' },
    { codename: 'delete_listingimage', name: 'Can delete listing image' },
    { codename: 'view_listinglocation', name: 'Can view listing location' },
    { codename: 'add_listinglocation', name: 'Can add listing location' },
    { codename: 'change_listinglocation', name: 'Can change listing location' },
    { codename: 'delete_listinglocation', name: 'Can delete listing location' },

    // Notifications
    { codename: 'view_notification', name: 'Can view notification' },
    { codename: 'add_notification', name: 'Can add notification' },
    { codename: 'change_notification', name: 'Can change notification' },
    { codename: 'delete_notification', name: 'Can delete notification' },
];
