export const allUniversityProgrammes = [
  "Business Management",
  "Accounting",
  "Finance",
  "Marketing",
  "Human Resource Management",
  "Entrepreneurship",
  "International Business",
  "Supply Chain Management",
  "Economics",
  "Risk Management & Insurance",
  "Audit and Risk Management",

  "Computer Science",
  "Information Technology",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Cybersecurity",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",

  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronic Engineering",
  "Industrial Engineering",
  "Chemical Engineering",
  "Biomedical Engineering",
  "Aerospace Engineering",
  "Environmental Engineering",

  "Medicine",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Physiotherapy",
  "Dentistry",
  "Biomedical Science",
  "Nutrition and Dietetics",
  "Medical Laboratory Science",

  "Psychology",
  "Sociology",
  "History",
  "Philosophy",
  "Linguistics",
  "Anthropology",
  "Literature",
  "International Relations",

  "Journalism",
  "Media Studies",
  "Public Relations",
  "Communication Studies",
  "Film and Television Production",
  "Graphic Design",

  "Early Childhood Education",
  "Primary Education",
  "Secondary Education",
  "Educational Psychology",
  "Curriculum Studies",
  "Special Needs Education",

  "Law (LLB)",
  "Criminology",
  "Public Administration",
  "Political Science",

  "Architecture",
  "Interior Design",
  "Urban and Regional Planning",
  "Landscape Architecture",
  "Industrial Design",

  "Agricultural Science",
  "Animal Science",
  "Horticulture",
  "Forestry",
  "Environmental Science",
  "Geography",
  "Geology",

  "Hospitality Management",
  "Tourism Management",
  "Event Management",
  "Culinary Arts",

  "Other Programmes",
];
