"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import socket
from dotenv import load_dotenv
import sys
import json

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG') == 'True'

# Add the apps directory to the Python path
sys.path.append(os.path.join(BASE_DIR, 'apps'))

# Allowed hosts
allowed_hosts = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts:
    ALLOWED_HOSTS = json.loads(allowed_hosts)


# Obscure the Admin URL
ADMIN_URL = 'super-secret-admin/' 

# CORS Configuration
CORS_ALLOW_CREDENTIALS = True
cors_allowed_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if cors_allowed_origins:
    CORS_ALLOWED_ORIGINS = json.loads(cors_allowed_origins)


if not DEBUG:
    # Security settings for behind proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_COOKIE_SECURE = True
    csrf_trusted_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if csrf_trusted_origins:
        CSRF_TRUSTED_ORIGINS = json.loads(csrf_trusted_origins)
    else:
        CSRF_TRUSTED_ORIGINS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party libraries
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'django_prometheus',
    'debug_toolbar',
    'imagekit',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
    # apps
    'users',
    'listings',
    'campuses',
    'interests',
    'health',
    'billing',
    'notifications',
    'analytics',
] 


ELASTICSEARCH_DSL = {
    'default': {
        'hosts': f"http://{os.environ.get('ELASTICSEARCH_HOST', 'localhost')}:9200",
        'http_auth': ('elastic', os.environ.get('ELASTIC_PASSWORD')),
        'request_timeout': 60
    },
}

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    
    # Custom
    'analytics.middleware.UserEngagementMiddleware',
] 




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    
}

if not DEBUG:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'listings': '100/day',
        'listing': '100/day',
        'dashboard_listings': '250/day',
        'rooms': '300/day',
        'inquiries': '100/hour',
        'user_lookup': '35/hour',
        'anon': '50/hour',  # Global anonymous throttle
        'user': '1000/hour',  # Global authenticated throttle
    }
else:
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'listings': '1000/hour',
        'listing': '1000/hour',
        'dashboard_listings': '1000/hour',
        'rooms': '1000/hour',
        'inquiries': '100/hour',
        'user_lookup': '1000/hour',
        'anon': '1000/hour',  # Global anonymous throttle
        'user': '1000/hour',  # Global authenticated throttle
    }


AUTH_USER_MODEL = 'users.User'


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'root'),
        'HOST': os.environ.get('PG_BOUNCER_HOST', 'pgbouncer'),
        'PORT': os.environ.get('PG_BOUNCER_PORT', 6432),
        'CONN_MAX_AGE': 0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Caching
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{os.environ.get('REDIS_PASSWORD')}@redis:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

CACHE_TTL = timedelta(days=1).total_seconds()  # 1 day

# ImageKit Configuration
IMAGEKIT_DEFAULT_IMAGE_KIT_ENGINE = 'imagekit.engines.Pillow'
IMAGEKIT_CACHE_BACKEND = 'default'
IMAGEKIT_CACHE_TIMEOUT = timedelta(days=30).total_seconds()

# Specify the cache directory
IMAGEKIT_CACHEFILE_DIR = 'CACHE/images'

# Ensure the cache directory exists
os.makedirs(os.path.join(MEDIA_ROOT, 'CACHE/images'), exist_ok=True)

# Internal IPs
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[:-1] + '1' for ip in ips] + ['127.0.0.1', 'localhost']

# Use the Docker-specific toolbar callback
DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': 'debug_toolbar.middleware.show_toolbar_with_docker',
    'SHOW_COLLAPSED': True,
    'RENDER_PANELS': True,
}

# Debug Toolbar Panels
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.alerts.AlertsPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]



