# Generated by Django 5.1.11 on 2025-07-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingamenity',
            name='value',
        ),
    ]
