# Generated by Django 5.2.4 on 2025-09-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0002_initial'),
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.landlord'),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_listings', to='campuses.neighborhood'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='room',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['campus', 'neighborhood', 'is_active', 'created_at'], name='listing_main_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_li_created_92fa22_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['listing', 'rent_per_month', 'gender_preference', 'max_occupants'], name='room_main_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['listing', 'max_occupants', 'current_occupants'], name='room_occupancy_check_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(condition=models.Q(('current_occupants__lt', models.F('max_occupants'))), fields=['rent_per_month', 'gender_preference'], name='available_rooms_idx'),
        ),
    ]
