# Generated by Django 5.2.4 on 2025-07-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Listings'},
        ),
    ]
