# Generated by Django 5.2.4 on 2025-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='listing',
            name='apply_agent_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
