# Generated by Django 5.1.11 on 2025-07-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listingamenity_value'),
        ('users', '0004_alter_landlord_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.landlord'),
        ),
    ]
