# Generated by Django 5.1.11 on 2025-07-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
