# Generated by Django 5.2.4 on 2025-10-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_room_options_listing_apply_agent_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Rooms'},
        ),
    ]
