# Generated by Django 5.2.4 on 2025-08-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any'), ('mixed', 'Mixed')], max_length=50),
        ),
    ]
