# Generated by Django 5.2.4 on 2025-11-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='face_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_face_image', to='listings.listingimage'),
        ),
    ]
