# Generated by Django 5.2.4 on 2025-08-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_rename_agents_campus_agent'),
        ('listings', '0005_alter_room_gender_preference'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['campus', 'neighborhood'], name='listings_li_campus__4edf72_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['campus', 'is_active'], name='listings_li_campus__419f20_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_li_created_92fa22_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['campus', 'neighborhood'], name='active_listings_location_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['listing', 'rent_per_month', 'gender_preference', 'max_occupants'], name='listings_ro_listing_841cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['rent_per_month'], name='listings_ro_rent_pe_5a1c53_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['gender_preference'], name='listings_ro_gender__2193df_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['max_occupants'], name='listings_ro_max_occ_047beb_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['max_occupants', 'current_occupants'], name='listings_ro_max_occ_0b8e81_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['listing', 'is_active'], name='listings_ro_listing_35db65_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(condition=models.Q(('current_occupants__lt', models.F('max_occupants'))), fields=['rent_per_month', 'gender_preference'], name='available_rooms_filter_idx'),
        ),
    ]
