# Generated by Django 5.2.4 on 2025-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='face_image',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='is_face_image',
            field=models.BooleanField(default=False),
        ),
    ]
