# Generated by Django 5.1.11 on 2025-07-13 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_alter_campus_options'),
        ('listings', '0005_alter_listing_campus_alter_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='campuses.neighborhood'),
        ),
    ]
