# Generated by Django 5.2.4 on 2025-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_amenitycategory_amenity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('connectivity', 'Connectivity & Utilities'), ('comfort', 'Room Comfort'), ('kitchen', 'Kitchen & Laundry'), ('common', 'Common Areas'), ('recreation', 'Recreation'), ('security', 'Security & Access')], default='common', max_length=50),
        ),
        migrations.DeleteModel(
            name='AmenityCategory',
        ),
    ]
