# Generated by Django 5.1.11 on 2025-07-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.amenity'),
        ),
    ]
