# Generated by Django 5.2.4 on 2025-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0006_alter_campus_city_alter_neighborhood_city'),
        ('listings', '0008_alter_amenity_category_delete_amenitycategory'),
        ('users', '0003_backfill_landlord_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_main_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_created_92fa22_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_main_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_occupancy_check_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='available_rooms_idx',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['campus', 'neighborhood', 'is_active'], name='listings_li_campus__1ff638_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['listing', 'rent_per_month', 'gender_preference'], name='listings_ro_listing_ec4e26_idx'),
        ),
    ]
