# Generated by Django 5.1.11 on 2025-07-14 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_alter_campus_options'),
        ('listings', '0009_alter_listing_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='campuses.campus'),
        ),
    ]
