# Generated by Django 5.1.11 on 2025-07-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_alter_campus_options'),
        ('listings', '0010_alter_listing_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='campuses.campus'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='campuses.neighborhood'),
        ),
    ]
