# Generated by Django... inside your_app/migrations/0002_...py

from django.db import migrations

def migrate_categories(apps, schema_editor):
    Amenity = apps.get_model('listings', 'Amenity')
    Category = apps.get_model('listings', 'Category')

    # The original choices hardcoded in your old model
    CATEGORY_CHOICES = [
        ('connectivity', 'Connectivity & Utilities'),
        ('comfort', 'Room Comfort'),
        ('kitchen', 'Kitchen & Laundry'),
        ('common', 'Common Areas'),
        ('recreation', 'Recreation'),
        ('security', 'Security & Access'),
    ]

    # 1. Create the Categories in the new table
    category_map = {}
    for name, display_name in CATEGORY_CHOICES:
        cat_obj, created = Category.objects.get_or_create(
            name=name,
            defaults={'display_name': display_name}
        )
        category_map[name] = cat_obj

    # 2. Update all existing Amenities
    for amenity in Amenity.objects.all():
        if amenity.category in category_map:
            amenity.new_category = category_map[amenity.category]
            amenity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_category_amenity_new_category'),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]

