# Generated by Django 5.2.4 on 2025-12-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20251209_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='category',
        ),
    ]
