# Generated by Django 5.2.4 on 2025-12-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_amenity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='new_category',
            new_name='category',
        ),
    ]
