# Generated by Django 5.1.11 on 2025-07-15 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0004_alter_campus_options'),
        ('listings', '0012_alter_listing_campus_alter_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_listings', to='campuses.campus'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_listings', to='campuses.neighborhood'),
        ),
    ]
