# Generated by Django 5.2.4 on 2025-07-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_campus_alter_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gender_preference',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='listingamenity',
            index=models.Index(fields=['amenity'], name='listings_li_amenity_26ebee_idx'),
        ),
        migrations.AddIndex(
            model_name='listingamenity',
            index=models.Index(fields=['listing'], name='listings_li_listing_918cb2_idx'),
        ),
    ]
