# Generated by Django 5.2.4 on 2025-12-09 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_new_category_amenity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='listings.category'),
        ),
    ]
