# Generated by Django 5.2.4 on 2025-07-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_room_gender_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
