# Generated by Django 5.2.4 on 2025-12-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_amenity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fuzzy_latitude', models.FloatField(blank=True, null=True)),
                ('fuzzy_longitude', models.FloatField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='listings.listing')),
            ],
        ),
    ]
