# Generated by Django 5.2.4 on 2025-07-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_remove_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_occupancy',
            new_name='max_occupants',
        ),
    ]
