# Generated by Django 5.2.4 on 2026-02-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_listinglocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
