# Generated by Django 5.2.4 on 2025-07-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_rename_max_occupancy_room_max_occupants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_occupancy',
            new_name='current_occupants',
        ),
    ]
