# Generated by Django 5.2.4 on 2025-07-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rent_per_month',
        ),
    ]
