name: Tangapano Development Environment

services:
  backend:
    container_name: backend_dev
    restart: always
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ENV=development
      - DB_HOST=db
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net
      - debug_toolbar_network

  frontend:
    container_name: frontend_dev
    restart: always
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/
    depends_on:
      - backend
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: db_dev
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_net

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer_dev
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    env_file:
      - .env
    ports:
      - "6432:6432"
    depends_on:
      - db
    networks:
      - app_net
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_net

volumes:
  postgres_data:
  static_volume:
  media_volume:
  node_modules_volume:
  redis_data:

networks:
  app_net:
    driver: bridge
  debug_toolbar_network:
    driver: bridge
    internal: false
