services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ENV=development
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - tangapano

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/
    depends_on:
      - backend
    networks:
      - tangapano

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - tangapano

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - tangapano

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  tangapano:
    driver: bridge
