services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      target: production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ENV=production
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - tangapano

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - tangapano

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - tangapano

  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tangapano

  backup:
    container_name: postgres_backup
    restart: always
    image: postgres:15
    depends_on:
      - db
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./backups:/backups
    entrypoint: >
      bash -c "apt-get update && apt-get install -y cron &&
               echo '0 2 * * * pg_dump -h db -U postgres postgres > /backups/db-$(date +\%F).sql && find /backups -type f -mtime +7 -delete' > /etc/crontab &&
               crontab /etc/crontab &&
               cron -f"

  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - tangapano

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  tangapano:
    driver: bridge
