name: Tangapano

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_ENV=development
      - ELASTICSEARCH_HOST=elasticsearch
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgbouncer
      - redis
    networks:
      - app_net
      - debug_toolbar_network

  # frontend:
  #   container_name: frontend
  #   restart: always
  #   build:
  #     context: ./frontend
  #     target: development
  #   volumes:
  #     - ./frontend:/app
  #     - node_modules_volume:/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:8000/api/
  #   depends_on:
  #     - backend
  #   networks:
  #     - app_net

  # frontend_v2:
  #   container_name: frontend_v2
  #   restart: always
  #   build:
  #     context: ./frontend_v2
  #     target: development
  #   volumes:
  #     - ./frontend_v2:/app
  #     - node_modules_volume:/app/node_modules
  #     # Persists the Next.js build cache so restarts are faster
  #     - /app/.next
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   environment:
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - NODE_ENV=development
  #     - NEXT_PUBLIC_API_URL=http://backend:8000/api/
  #   depends_on:
  #     - backend
  #   networks:
  #     - app_net

  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_net

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.0-p0
    container_name: pgbouncer
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    env_file:
      - .env
    ports:
      - "6432:6432"
    depends_on:
      - db
    networks:
      - app_net
    restart: unless-stopped

  backup:
    build: ./backup
    container_name: backup
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MEGA_DB_FOLDER=db-daily-backups-test
      - MEGA_IMAGES_FOLDER=media-weekly-backups-test
      - PACK_ALL_INTO_ONE_ZIP=false
    volumes:
      - media_volume:/app/media
    restart: unless-stopped
    networks:
      - app_net
    profiles: ["backup"]

  db-restore:
    build: ./restore
    container_name: db_restore
    env_file:
      - .env
    environment:
      - MEGA_DB_FOLDER=db-daily-backups-test
      - MEGA_IMAGES_FOLDER=media-weekly-backups-test
    depends_on:
      - db
    networks:
      - app_net
    command: ["/app/docker-db-restore.sh"]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    profiles: ["restore"]

  images-restore:
    build: ./restore
    container_name: images_restore
    env_file:
      - .env
    environment:
      - MEGA_DB_FOLDER=db-daily-backups-test
      - MEGA_IMAGES_FOLDER=media-weekly-backups-test
    volumes:
      - media_volume:/app/media
    networks:
      - app_net
    command: ["/app/docker-images-restore.sh"]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    profiles: ["restore"]

  redis:
    container_name: redis
    image: redis:8.2.1
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_net

  # --- Elasticsearch Service ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    labels:
      "com.tangapano.service": "elasticsearch"
    networks:
      - app_net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_net

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      # - frontend
      - backend
    restart: always
    networks:
      - app_net
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_net
    profiles: ["metrics"]

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "9001:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app_net
    profiles: ["metrics"]

volumes:
  postgres_data:
  es_data:
  prometheus_data:
  grafana_data:
  static_volume:
  media_volume:
  # node_modules_volume:
  redis_data:

networks:
  app_net:
    driver: bridge
  debug_toolbar_network:
    driver: bridge
    internal: false
