# Generated by Django 5.2.4 on 2025-12-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('employee_created', 'Employee Created'), ('employee_updated', 'Employee Updated'), ('landlord_created', 'Landlord Created'), ('landlord_updated', 'Landlord Updated'), ('landlord_verified', 'Landlord Verified'), ('landlord_unverified', 'Landlord Unverified'), ('user_registered', 'User Registered'), ('admin_login', 'Admin Login'), ('admin_temp_auth', 'Admin Privileged Auth'), ('listing_locked', 'Listing Locked'), ('listing_unlocked', 'Listing Unlocked'), ('campus_created', 'Campus Created'), ('campus_updated', 'Campus Updated'), ('city_created', 'City Created'), ('city_updated', 'City Updated'), ('neighborhood_created', 'Neighborhood Created'), ('neighborhood_updated', 'Neighborhood Updated')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
