# Generated by Django 5.2.4 on 2025-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('agency', 'Agency/Company')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
