# Generated by Django 5.2.4 on 2025-12-04 00:25

from django.db import migrations
from django.db.models import Q

def set_account_types(apps, schema_editor):
    # We must get the model from 'apps' to ensure we use the version 
    # of the model that exists at this point in history.
    Landlord = apps.get_model('users', 'Landlord')
    
    # 1. Update Agencies
    # Logic: If company_name is NOT null and NOT an empty string
    qs_agencies = Landlord.objects.exclude(
        Q(company_name__isnull=True) | Q(company_name__exact='')
    )
    updated_count = qs_agencies.update(account_type='agency')
    
    print(f"\nUpdated {updated_count} landlords to 'Agency' account type.")

def reverse_account_types(apps, schema_editor):
    # If we un-apply this migration, we don't strictly need to do anything
    # because the column would eventually be deleted by the previous migration reverse.
    # But generally, we can just pass.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_landlord_account_type_landlord_is_verified_and_more'),
    ]

    operations = [
    ]
