# Generated by Django 5.1.11 on 2025-07-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
