# Generated by Django 5.1.11 on 2025-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agent_agent_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
