# Generated by Django 5.2.4 on 2025-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_alter_listing_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contacted_agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interests', to='users.agent')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listings.room')),
            ],
        ),
    ]
