# Generated by Django 5.2.4 on 2025-09-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='contacted_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interests', to='users.agent'),
        ),
        migrations.AddField(
            model_name='interest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listings.room'),
        ),
    ]
