# Generated by Django 5.2.4 on 2025-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='deposit_readiness',
            field=models.CharField(choices=[('ready_now', 'Yes, ready to pay deposit'), ('within_24h', 'Will arrange within 24 hours'), ('need_time', 'Need more time to arrange funds')], default='ready_now', max_length=20),
        ),
        migrations.AddField(
            model_name='interest',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='move_in_timeline',
            field=models.CharField(choices=[('immediately', 'Immediately (within 1 week)'), ('2_weeks', 'Within 2 weeks'), ('1_month', 'Within 1 month'), ('next_semester', 'Next Semester')], default='immediately', max_length=20),
        ),
        migrations.AddField(
            model_name='interest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Payment'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='interest',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='program',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='year_of_study',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
