# Generated by Django 5.2.4 on 2025-10-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_interest_agree_to_terms_interest_deposit_readiness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='student_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='year_of_study',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
