# Generated by Django 5.2.4 on 2025-12-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0004_alter_interest_full_name_alter_interest_phone_number_and_more'),
        ('users', '0003_backfill_landlord_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='contacted_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_interests', to='users.agent'),
        ),
    ]
