# Generated by Django 5.2.4 on 2025-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_alter_interest_contacted_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing', 'Viewing Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
