from .user_serializer import UserSerializer
from .registration_serializer import UserRegistrationSerializer
from .landlord_serializer import LandlordSerializer
from .agent_serializer import AgentSerializer
from .agent_write_serializer import AgentWriteSerializer
from .department_serializer import DepartmentSerializer
from .role_serializer import RoleSerializer, PermissionSerializer
from .employee_serializer import EmployeeSerializer
from .simple_user_serializer import SimpleUserSerializer
from .change_password_serializer import ChangePasswordSerializer

