# Generated by Django 5.1.11 on 2025-07-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='neighborhoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campuses.neighborhood'),
        ),
    ]
