# Generated by Django 5.2.4 on 2025-09-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent'),
        ),
        migrations.AddField(
            model_name='campus',
            name='neighborhoods',
            field=models.ManyToManyField(blank=True, related_name='campuses', to='campuses.neighborhood'),
        ),
    ]
