# Generated by Django 5.2.4 on 2025-08-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='agents',
            new_name='agent',
        ),
    ]
