# Generated by Django 5.1.11 on 2025-07-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_campus_neighborhoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='neighborhoods',
        ),
        migrations.AddField(
            model_name='campus',
            name='neighborhoods',
            field=models.ManyToManyField(blank=True, related_name='campuses', to='campuses.neighborhood'),
        ),
    ]
