# Generated by Django 5.1.11 on 2025-07-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_remove_campus_neighborhoods_campus_neighborhoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
    ]
