# Generated by Django 5.2.4 on 2025-12-04 02:27

from django.db import migrations


def move_data(apps, schema_editor):
    Campus = apps.get_model('campuses', 'Campus')
    Neighborhood = apps.get_model('campuses', 'Neighborhood')
    City = apps.get_model('campuses', 'City')

    # 1. Transfer Campus Data
    for c in Campus.objects.all():
        if c.city: # If the string field has text
            city_obj, _ = City.objects.get_or_create(name=c.city.strip())
            c.new_city = city_obj
            c.save()

    # 2. Transfer Neighborhood Data
    for n in Neighborhood.objects.all():
        if n.city:
            city_obj, _ = City.objects.get_or_create(name=n.city.strip())
            n.new_city = city_obj
            n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_city_campus_new_city_neighborhood_new_city'),
    ]

    operations = [
        migrations.RunPython(move_data),
    ]
