# Generated by Django 5.2.4 on 2025-12-04 02:34

from django.db import migrations

class Migration(migrations.Migration):
    
    dependencies = [
        ('campuses', '0004_transfer_city_data'),
    ]

    operations = [
        # --- CAMPUS OPERATIONS ---
        # 1. Remove the old String field
        migrations.RemoveField(
            model_name='campus',
            name='city',
        ),
        # 2. Rename the new FK field to 'city'
        migrations.RenameField(
            model_name='campus',
            old_name='new_city',
            new_name='city',
        ),
        
        # --- NEIGHBORHOOD OPERATIONS ---
        # 3. Remove the old String field
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        # 4. Rename the new FK field to 'city'
        migrations.RenameField(
            model_name='neighborhood',
            old_name='new_city',
            new_name='city',
        ),
    ]

    
