# Generated by Django 5.2.4 on 2025-12-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0005_finalize_city_swap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campuses_in_city', to='campuses.city'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='campuses.city'),
        ),
    ]
