# Generated by Django 5.2.4 on 2025-12-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0007_alter_campus_agent'),
        ('users', '0003_backfill_landlord_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus', to='users.agent'),
        ),
    ]
