# Generated by Django 5.2.4 on 2025-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0008_alter_campus_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='campuses.city'),
        ),
    ]
