# Generated by Django 5.2.4 on 2025-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0009_alter_campus_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='latitude',
            field=models.FloatField(default=0, help_text='Exact GPS Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campus',
            name='longitude',
            field=models.FloatField(default=0, help_text='Exact GPS Longitude'),
            preserve_default=False,
        ),
    ]
