# Generated by Django 5.2.4 on 2025-12-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0010_campus_latitude_campus_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Exact GPS Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Exact GPS Longitude', null=True),
        ),
    ]
